<?php

namespace AppBundle\Repository;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUpcoming()
    {
        return
            $this->getEntityManager()
                ->createQuery("SELECT u FROM AppBundle:Lesson u WHERE u.date > CURRENT_DATE ()")
                ->getResult();
    }
}
