<?php

namespace AppBundle\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMembers()
    {
        return
            $this->getEntityManager()
                ->createQuery("SELECT m FROM AppBundle:Person m WHERE m.is_member = 1")
                ->getResult();
    }

    public function findInstructors()
    {
        return
            $this->getEntityManager()
                ->createQuery("SELECT m FROM AppBundle:Person m WHERE m.is_instructor = 1")
                ->getResult();
    }
}
