<?php

namespace AppBundle\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSpecific($userId, $lessonId)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT m FROM AppBundle:Registration m JOIN m.person p JOIN m.lesson l WHERE l.id = $lessonId AND p.id = $userId")
            ->getSingleResult();
    }
}
